const GET_OWNERS_REQUESTED = 'app/owner/GET_OWNERS_REQUESTED'
const GET_OWNERS_SUCCESS = 'app/owner/GET_OWNERS_SUCCESS'
const GET_OWNERS_ERROR = 'app/owner/GET_OWNERS_ERROR'

export default {
  GET_OWNERS_REQUESTED,
  GET_OWNERS_SUCCESS,
  GET_OWNERS_ERROR,
}